In [3]:
import numpy as np
from scipy.linalg import expm
A = np.array([[0, 1, 0, 0],
              [0, 0, -88.6, -0.7],
              [0, 0, 0, 1],
              [6333.3, 250, -7110.8, -256.3]])
t = 0.1
phi = expm(np.array(A) * t)
print(phi)


[[ 7.76666690e-01  8.46070110e-02 -1.56188337e-01 -8.06686104e-04]
 [-5.10898510e+00  5.74995164e-01 -1.75999763e+00 -8.65959623e-03]
 [ 6.45285395e-01  7.80372231e-02 -9.48818652e-02 -5.25220482e-04]
 [-3.32637888e+00  5.13980275e-01 -3.17936016e+00 -1.48939119e-02]]
